/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletProfileRouteImport } from './routes/wallet.profile'
import { Route as WalletBusinessIdRouteImport } from './routes/wallet.$businessId'
import { Route as UserRegisterRouteImport } from './routes/user.register'
import { Route as UserDashboardRouteImport } from './routes/user.dashboard'
import { Route as SettingsBusinessIdRouteImport } from './routes/settings.$businessId'
import { Route as JoinBusinessIdRouteImport } from './routes/join.$businessId'
import { Route as DashboardBusinessIdRouteImport } from './routes/dashboard.$businessId'
import { Route as CampaignsBusinessIdRouteImport } from './routes/campaigns.$businessId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DashboardBusinessIdVisitsRouteImport } from './routes/dashboard.$businessId.visits'
import { Route as DashboardBusinessIdRedemptionsRouteImport } from './routes/dashboard.$businessId.redemptions'
import { Route as DashboardBusinessIdClientsRouteImport } from './routes/dashboard.$businessId.clients'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletProfileRoute = WalletProfileRouteImport.update({
  id: '/wallet/profile',
  path: '/wallet/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletBusinessIdRoute = WalletBusinessIdRouteImport.update({
  id: '/wallet/$businessId',
  path: '/wallet/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRegisterRoute = UserRegisterRouteImport.update({
  id: '/user/register',
  path: '/user/register',
  getParentRoute: () => rootRouteImport,
} as any)
const UserDashboardRoute = UserDashboardRouteImport.update({
  id: '/user/dashboard',
  path: '/user/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsBusinessIdRoute = SettingsBusinessIdRouteImport.update({
  id: '/settings/$businessId',
  path: '/settings/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinBusinessIdRoute = JoinBusinessIdRouteImport.update({
  id: '/join/$businessId',
  path: '/join/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessIdRoute = DashboardBusinessIdRouteImport.update({
  id: '/dashboard/$businessId',
  path: '/dashboard/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsBusinessIdRoute = CampaignsBusinessIdRouteImport.update({
  id: '/campaigns/$businessId',
  path: '/campaigns/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessIdVisitsRoute =
  DashboardBusinessIdVisitsRouteImport.update({
    id: '/visits',
    path: '/visits',
    getParentRoute: () => DashboardBusinessIdRoute,
  } as any)
const DashboardBusinessIdRedemptionsRoute =
  DashboardBusinessIdRedemptionsRouteImport.update({
    id: '/redemptions',
    path: '/redemptions',
    getParentRoute: () => DashboardBusinessIdRoute,
  } as any)
const DashboardBusinessIdClientsRoute =
  DashboardBusinessIdClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => DashboardBusinessIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$businessId': typeof CampaignsBusinessIdRoute
  '/dashboard/$businessId': typeof DashboardBusinessIdRouteWithChildren
  '/join/$businessId': typeof JoinBusinessIdRoute
  '/settings/$businessId': typeof SettingsBusinessIdRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/register': typeof UserRegisterRoute
  '/wallet/$businessId': typeof WalletBusinessIdRoute
  '/wallet/profile': typeof WalletProfileRoute
  '/wallet/': typeof WalletIndexRoute
  '/dashboard/$businessId/clients': typeof DashboardBusinessIdClientsRoute
  '/dashboard/$businessId/redemptions': typeof DashboardBusinessIdRedemptionsRoute
  '/dashboard/$businessId/visits': typeof DashboardBusinessIdVisitsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$businessId': typeof CampaignsBusinessIdRoute
  '/dashboard/$businessId': typeof DashboardBusinessIdRouteWithChildren
  '/join/$businessId': typeof JoinBusinessIdRoute
  '/settings/$businessId': typeof SettingsBusinessIdRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/register': typeof UserRegisterRoute
  '/wallet/$businessId': typeof WalletBusinessIdRoute
  '/wallet/profile': typeof WalletProfileRoute
  '/wallet': typeof WalletIndexRoute
  '/dashboard/$businessId/clients': typeof DashboardBusinessIdClientsRoute
  '/dashboard/$businessId/redemptions': typeof DashboardBusinessIdRedemptionsRoute
  '/dashboard/$businessId/visits': typeof DashboardBusinessIdVisitsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/$businessId': typeof CampaignsBusinessIdRoute
  '/dashboard/$businessId': typeof DashboardBusinessIdRouteWithChildren
  '/join/$businessId': typeof JoinBusinessIdRoute
  '/settings/$businessId': typeof SettingsBusinessIdRoute
  '/user/dashboard': typeof UserDashboardRoute
  '/user/register': typeof UserRegisterRoute
  '/wallet/$businessId': typeof WalletBusinessIdRoute
  '/wallet/profile': typeof WalletProfileRoute
  '/wallet/': typeof WalletIndexRoute
  '/dashboard/$businessId/clients': typeof DashboardBusinessIdClientsRoute
  '/dashboard/$businessId/redemptions': typeof DashboardBusinessIdRedemptionsRoute
  '/dashboard/$businessId/visits': typeof DashboardBusinessIdVisitsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/scan'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/campaigns/$businessId'
    | '/dashboard/$businessId'
    | '/join/$businessId'
    | '/settings/$businessId'
    | '/user/dashboard'
    | '/user/register'
    | '/wallet/$businessId'
    | '/wallet/profile'
    | '/wallet/'
    | '/dashboard/$businessId/clients'
    | '/dashboard/$businessId/redemptions'
    | '/dashboard/$businessId/visits'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/scan'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/campaigns/$businessId'
    | '/dashboard/$businessId'
    | '/join/$businessId'
    | '/settings/$businessId'
    | '/user/dashboard'
    | '/user/register'
    | '/wallet/$businessId'
    | '/wallet/profile'
    | '/wallet'
    | '/dashboard/$businessId/clients'
    | '/dashboard/$businessId/redemptions'
    | '/dashboard/$businessId/visits'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/privacy'
    | '/reset-password'
    | '/scan'
    | '/signup'
    | '/terms'
    | '/auth/callback'
    | '/campaigns/$businessId'
    | '/dashboard/$businessId'
    | '/join/$businessId'
    | '/settings/$businessId'
    | '/user/dashboard'
    | '/user/register'
    | '/wallet/$businessId'
    | '/wallet/profile'
    | '/wallet/'
    | '/dashboard/$businessId/clients'
    | '/dashboard/$businessId/redemptions'
    | '/dashboard/$businessId/visits'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScanRoute: typeof ScanRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CampaignsBusinessIdRoute: typeof CampaignsBusinessIdRoute
  DashboardBusinessIdRoute: typeof DashboardBusinessIdRouteWithChildren
  JoinBusinessIdRoute: typeof JoinBusinessIdRoute
  SettingsBusinessIdRoute: typeof SettingsBusinessIdRoute
  UserDashboardRoute: typeof UserDashboardRoute
  UserRegisterRoute: typeof UserRegisterRoute
  WalletBusinessIdRoute: typeof WalletBusinessIdRoute
  WalletProfileRoute: typeof WalletProfileRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/profile': {
      id: '/wallet/profile'
      path: '/wallet/profile'
      fullPath: '/wallet/profile'
      preLoaderRoute: typeof WalletProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$businessId': {
      id: '/wallet/$businessId'
      path: '/wallet/$businessId'
      fullPath: '/wallet/$businessId'
      preLoaderRoute: typeof WalletBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/register': {
      id: '/user/register'
      path: '/user/register'
      fullPath: '/user/register'
      preLoaderRoute: typeof UserRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/dashboard': {
      id: '/user/dashboard'
      path: '/user/dashboard'
      fullPath: '/user/dashboard'
      preLoaderRoute: typeof UserDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$businessId': {
      id: '/settings/$businessId'
      path: '/settings/$businessId'
      fullPath: '/settings/$businessId'
      preLoaderRoute: typeof SettingsBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$businessId': {
      id: '/join/$businessId'
      path: '/join/$businessId'
      fullPath: '/join/$businessId'
      preLoaderRoute: typeof JoinBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$businessId': {
      id: '/dashboard/$businessId'
      path: '/dashboard/$businessId'
      fullPath: '/dashboard/$businessId'
      preLoaderRoute: typeof DashboardBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$businessId': {
      id: '/campaigns/$businessId'
      path: '/campaigns/$businessId'
      fullPath: '/campaigns/$businessId'
      preLoaderRoute: typeof CampaignsBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$businessId/visits': {
      id: '/dashboard/$businessId/visits'
      path: '/visits'
      fullPath: '/dashboard/$businessId/visits'
      preLoaderRoute: typeof DashboardBusinessIdVisitsRouteImport
      parentRoute: typeof DashboardBusinessIdRoute
    }
    '/dashboard/$businessId/redemptions': {
      id: '/dashboard/$businessId/redemptions'
      path: '/redemptions'
      fullPath: '/dashboard/$businessId/redemptions'
      preLoaderRoute: typeof DashboardBusinessIdRedemptionsRouteImport
      parentRoute: typeof DashboardBusinessIdRoute
    }
    '/dashboard/$businessId/clients': {
      id: '/dashboard/$businessId/clients'
      path: '/clients'
      fullPath: '/dashboard/$businessId/clients'
      preLoaderRoute: typeof DashboardBusinessIdClientsRouteImport
      parentRoute: typeof DashboardBusinessIdRoute
    }
  }
}

interface DashboardBusinessIdRouteChildren {
  DashboardBusinessIdClientsRoute: typeof DashboardBusinessIdClientsRoute
  DashboardBusinessIdRedemptionsRoute: typeof DashboardBusinessIdRedemptionsRoute
  DashboardBusinessIdVisitsRoute: typeof DashboardBusinessIdVisitsRoute
}

const DashboardBusinessIdRouteChildren: DashboardBusinessIdRouteChildren = {
  DashboardBusinessIdClientsRoute: DashboardBusinessIdClientsRoute,
  DashboardBusinessIdRedemptionsRoute: DashboardBusinessIdRedemptionsRoute,
  DashboardBusinessIdVisitsRoute: DashboardBusinessIdVisitsRoute,
}

const DashboardBusinessIdRouteWithChildren =
  DashboardBusinessIdRoute._addFileChildren(DashboardBusinessIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScanRoute: ScanRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CampaignsBusinessIdRoute: CampaignsBusinessIdRoute,
  DashboardBusinessIdRoute: DashboardBusinessIdRouteWithChildren,
  JoinBusinessIdRoute: JoinBusinessIdRoute,
  SettingsBusinessIdRoute: SettingsBusinessIdRoute,
  UserDashboardRoute: UserDashboardRoute,
  UserRegisterRoute: UserRegisterRoute,
  WalletBusinessIdRoute: WalletBusinessIdRoute,
  WalletProfileRoute: WalletProfileRoute,
  WalletIndexRoute: WalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
