/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletBusinessIdRouteImport } from './routes/wallet.$businessId'
import { Route as DashboardBusinessIdRouteImport } from './routes/dashboard.$businessId'
import { Route as CampaignsBusinessIdRouteImport } from './routes/campaigns.$businessId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/wallet/',
  path: '/wallet/',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletBusinessIdRoute = WalletBusinessIdRouteImport.update({
  id: '/wallet/$businessId',
  path: '/wallet/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBusinessIdRoute = DashboardBusinessIdRouteImport.update({
  id: '/dashboard/$businessId',
  path: '/dashboard/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsBusinessIdRoute = CampaignsBusinessIdRouteImport.update({
  id: '/campaigns/$businessId',
  path: '/campaigns/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/campaigns/$businessId': typeof CampaignsBusinessIdRoute
  '/dashboard/$businessId': typeof DashboardBusinessIdRoute
  '/wallet/$businessId': typeof WalletBusinessIdRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/campaigns/$businessId': typeof CampaignsBusinessIdRoute
  '/dashboard/$businessId': typeof DashboardBusinessIdRoute
  '/wallet/$businessId': typeof WalletBusinessIdRoute
  '/wallet': typeof WalletIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/scan': typeof ScanRoute
  '/signup': typeof SignupRoute
  '/campaigns/$businessId': typeof CampaignsBusinessIdRoute
  '/dashboard/$businessId': typeof DashboardBusinessIdRoute
  '/wallet/$businessId': typeof WalletBusinessIdRoute
  '/wallet/': typeof WalletIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/scan'
    | '/signup'
    | '/campaigns/$businessId'
    | '/dashboard/$businessId'
    | '/wallet/$businessId'
    | '/wallet/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/scan'
    | '/signup'
    | '/campaigns/$businessId'
    | '/dashboard/$businessId'
    | '/wallet/$businessId'
    | '/wallet'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/scan'
    | '/signup'
    | '/campaigns/$businessId'
    | '/dashboard/$businessId'
    | '/wallet/$businessId'
    | '/wallet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ScanRoute: typeof ScanRoute
  SignupRoute: typeof SignupRoute
  CampaignsBusinessIdRoute: typeof CampaignsBusinessIdRoute
  DashboardBusinessIdRoute: typeof DashboardBusinessIdRoute
  WalletBusinessIdRoute: typeof WalletBusinessIdRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/wallet'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/$businessId': {
      id: '/wallet/$businessId'
      path: '/wallet/$businessId'
      fullPath: '/wallet/$businessId'
      preLoaderRoute: typeof WalletBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$businessId': {
      id: '/dashboard/$businessId'
      path: '/dashboard/$businessId'
      fullPath: '/dashboard/$businessId'
      preLoaderRoute: typeof DashboardBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/$businessId': {
      id: '/campaigns/$businessId'
      path: '/campaigns/$businessId'
      fullPath: '/campaigns/$businessId'
      preLoaderRoute: typeof CampaignsBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ScanRoute: ScanRoute,
  SignupRoute: SignupRoute,
  CampaignsBusinessIdRoute: CampaignsBusinessIdRoute,
  DashboardBusinessIdRoute: DashboardBusinessIdRoute,
  WalletBusinessIdRoute: WalletBusinessIdRoute,
  WalletIndexRoute: WalletIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
